---
- name: Ensure keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Syncthing GPG key
  become: true
  ansible.builtin.get_url:
    url: https://syncthing.net/release-key.txt
    dest: /etc/apt/keyrings/syncthing.asc
    mode: '0644'
    force: true

- name: Add Syncthing repository
  become: true
  ansible.builtin.deb822_repository:
    name: syncthing
    types: [deb]
    uris: "https://apt.syncthing.net/"
    signed_by: /etc/apt/keyrings/syncthing.asc
    suites: [syncthing]
    components: [stable]
    state: present

- name: Install Syncthing
  become: true
  ansible.builtin.apt:
    name: syncthing
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable systemd syncthing@.service
  become: true
  ansible.builtin.systemd_service:
    name: "syncthing@{{ ansible_env.USER }}.service"
    enabled: true
  notify:
    - Start Syncthing service
