---
- name: Install local machine
  hosts: all
  vars_files:
    - config.yaml
  roles:
    - system-base
    # - dev-tools
    # - vscode
    # - docker
    # - btop
    # ======== #
    # GPU only #
    # ======== #
    # - nvidia
    # ================ #
    # Personal machine #
    # ================ #
    # - gnome
    # - obsidian
    # - syncthing
    # - wine
    # - paperless-ngx
    # - retroarch
    # - latex
    # - battery
