---
- name: Install base system
  hosts: all
  become: true
  vars_files:
    - config.yaml
  roles:
    - { role: preflight, tags: [preflight] }
    - { role: system-base, tags: [base] }
    - { role: vscode, tags: [vscode] }
    # - updates
    - { role: security, tags: [security] }
    - { role: firmware, tags: [firmware] }
    - { role: summary, tags: [summary] }
