---
- name: Install workloads
  hosts: all
  become: true
  vars_files:
    - config.yaml
  roles:
    - { role: preflight, tags: [preflight] }
    - { role: docker, tags: [docker] }
    - { role: summary, tags: [summary] }
